name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install
      working-directory: ./btc-latest-blocks
    - name: Run tests
      run: npm test
      working-directory: ./btc-latest-blocks

    - name: Build
      run: npm run build
      working-directory: ./btc-latest-blocks

    # Add additional steps for deployment if needed
